apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kuard-config
  labels:
    app: kuard-config
  annotations:
    deployment.kubernetes.io/revision: "1"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard-config
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kuard-config
      annotations:
        kubernetes.io/change-cause: "new deployment"
    spec:
      containers:
        - image: docker.io/dlneintr/kuard:latest
          name: test-container
          imagePullPolicy: Always
          command:
            - "/kuard"
            - "$(EXTRA_PARAM)"
          env:
            - name: ANOTHER_PARAM
              valueFrom: 
                configMapKeyRef:
                  name: my-config
                  key: another-param
            - name: EXTRA_PARAM
              valueFrom: 
                configMapKeyRef:
                  name: my-config
                  key: extra-param
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: my-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: kuard-config
  labels:
    app: kuard-config
spec:
  type: NodePort 
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    #nodePort: 31010
  selector:
    app: kuard-config
    #
