apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: docker.io/dlneintr/kuard:latest
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
